openapi: 3.0.1
info:
  title: ng-resume API Documentation
  contact:
    name: J. Patrick Fulton
    url: https://github.com/jpfulton/
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  version: '1.0'
servers:
  - url: /api/
paths:
  /education:
    get:
      tags:
        - education
      operationId: EducationGetAll
      responses:
        '200':
          description: An array of all education items.
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/education'
  '/education/{id}':
    get:
      tags:
        - education
      operationId: EducationGetById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: An education item by its id property.
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/education'
  /test:
    get:
      tags:
        - test
      operationId: TestGet
      parameters:
        - name: name
          in: query
          schema:
            type: string
      responses:
        '200':
          description: A formatted test string.
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
  /workhistory:
    get:
      tags:
        - workhistory
      operationId: WorkHistoryGetAll
      responses:
        '200':
          description: An array of all work history items.
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/workHistory'
  '/workhistory/{id}':
    get:
      tags:
        - workhistory
      operationId: WorkHistoryGetById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A work history item by its id property.
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/workHistory'
components:
  schemas:
    education:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        subtitle:
          type: string
        organization:
          type: string
    workHistory:
      type: object
      properties:
        id:
          type: string
          format: uuid
        startYear:
          type: integer
          format: int32
        endYear:
          type: integer
          format: int32
        title:
          type: string
        organization:
          type: string
        organizationURL:
          type: string
        bullets:
          type: array
          items:
            type: string
        skills:
          type: array
          items:
            type: string