name: continous-integration-and-deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_LOCATION: "/ng-resume/dist/ng-resume" # location of your client code
  API_LOCATION: "" # location of your api source code - optional
  APP_ARTIFACT_LOCATION: "/ng-resume/dist/ng-resume" # location of client code build output
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing deployment token for your static web app
  
jobs:
  build-lint-test-deploy:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'

        - name: Install dependencies via yarn with frozen lockfile
          working-directory: ng-resume
          run: yarn --frozen-lockfile

        - name: Lint application
          working-directory: ng-resume
          run: yarn run lint

        - name: Build application
          working-directory: ng-resume
          run: yarn run build

        - name: Test application
          working-directory: ng-resume
          run: yarn run test --configuration=ci

        - name: Deploy
          uses: Azure/static-web-apps-deploy@v1
          with:
            azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
            action: "upload"
            skip_app_build: true
            skip_api_build: true
            ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
            # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
            app_location: ${{ env.APP_LOCATION }} # App source code path
            api_location: ${{ env.API_LOCATION }} # Api source code path - optional
            app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
            #output_location: "" # Built app content directory - optional
            ###### End of Repository/Build Configurations ######